### ISSUE TITLE
Cypress 10 release.

### ISSUE THREAD

**Issue by 0itsed** [Clebiez/cypress-maildev#5]
Cypress Team introduced several breaking changes to the Cypress configuration file. Using a **cypress.json** configuration file **is no longer supported** so there is no way to specify your maildev address.

**Comment by robertjarske** [comment]
> Cypress Team introduced several breaking changes to the Cypress configuration file. Using a **cypress.json** configuration file **is no longer supported** so there is no way to specify your maildev address.

You should be able to do something like this as suggested in the cypress documentation https://docs.cypress.io/guides/guides/environment-variables#Option-1-configuration-file
```javascript
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  projectId: '128076ed-9868-4e98-9cef-98dd8b705d75',
  env: {
    login_url: '/login',
    products_url: '/products'
  }
})
```

**Comment by Clebiez** [comment]
Readme has been updated according to the Cypress documentation, thanks for this issue.
