### ISSUE TITLE
maildev commands not being registerd in Cypress 10.3

### ISSUE THREAD

**Issue by jprealini** [Clebiez/cypress-maildev#7]
Hi! I found your plugin and I'm trying to implement it in a Cypress 10.3 solution. 

My problem is that no matter how I try loading the plugin (in the support/e2e.ts file, or in the SetupNodeEvents section in the configuration file) the "cy" commands are not being registered... 

I mean, when I put cy.maildevGetLastMessage() I get an error saying that there is no such command

"Property 'maildevGetLastMessage' does not exist on type 'cy & CyEventEmitter'.ts(2339)"

Any hint?

Thanks

**Comment by Clebiez** [comment]
Hi !
Do you get this error directly inside your IDE or nothing is linted inside it and tests just crash ?
Using typescript is not actually available. I mean, the code will works but TS can't recognize theses new commands

https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands

I will try to implement an interface as soon as possible

**Comment by Clebiez** [comment]
Hey @jprealini, I just released v1.3 which implement TS support.
It should be resolved now.

**Comment by jprealini** [comment]
@Clebiez thanks! Back then when you sent the response in November I was able to implement the workaround you recommended. 
I will try the new version now, just for fun! 😄 
Thanks!
